### ISSUE TITLE
tuple index error

### ISSUE THREAD

**Issue by EricZimmerman** [raptIRJuan/RecentDocsMRU#1]
```
C:\Temp
λ c:\Python27\python.exe c:\Temp\recentdocs-mru.py -f d:\Temp\win10ERZamcachepreso\NTUSER.DAT
Traceback (most recent call last):
  File "c:\Temp\recentdocs-mru.py", line 82, in <module>
    main()
  File "c:\Temp\recentdocs-mru.py", line 63, in main
    mru0 = str(parse_MRUListEx(subkey.value('MRUListEx').value())[0])
IndexError: tuple index out of range
```

i have had other hives process fine

**Comment by raptIRJuan** [comment]
Should be fixed now. Thanks for reporting it.
